import type { Patient } from "../../types/patient";

export const mockPatients: Patient[] = [
  {
    id: "p001",
    name: "Rahul Sharma",
    age: 45,
    gender: "Male",
    condition: "Hypertension",
    status: "Stable",
    doctor: "Dr. Mehta",
    admittedOn: "2024-04-10",
    avatar: "RS",
  },
  {
    id: "p002",
    name: "Priya Patel",
    age: 32,
    gender: "Female",
    condition: "Diabetes Type 2",
    status: "Recovering",
    doctor: "Dr. Sharma",
    admittedOn: "2024-04-15",
    avatar: "PP",
  },
  {
    id: "p003",
    name: "Amit Verma",
    age: 58,
    gender: "Male",
    condition: "Cardiac Arrest",
    status: "Critical",
    doctor: "Dr. Mehta",
    admittedOn: "2024-04-18",
    avatar: "AV",
  },
  {
    id: "p004",
    name: "Sneha Iyer",
    age: 27,
    gender: "Female",
    condition: "Appendicitis",
    status: "Discharged",
    doctor: "Dr. Rao",
    admittedOn: "2024-04-12",
    avatar: "SI",
  },
  {
    id: "p005",
    name: "Vikram Singh",
    age: 63,
    gender: "Male",
    condition: "Kidney Failure",
    status: "Critical",
    doctor: "Dr. Sharma",
    admittedOn: "2024-04-20",
    avatar: "VS",
  },
  {
    id: "p006",
    name: "Ananya Gupta",
    age: 39,
    gender: "Female",
    condition: "Pneumonia",
    status: "Stable",
    doctor: "Dr. Rao",
    admittedOn: "2024-04-19",
    avatar: "AG",
  },
  {
    id: "p007",
    name: "Rohan Das",
    age: 51,
    gender: "Male",
    condition: "Fracture",
    status: "Recovering",
    doctor: "Dr. Mehta",
    admittedOn: "2024-04-17",
    avatar: "RD",
  },
  {
    id: "p008",
    name: "Meera Nair",
    age: 44,
    gender: "Female",
    condition: "Migraine",
    status: "Stable",
    doctor: "Dr. Sharma",
    admittedOn: "2024-04-21",
    avatar: "MN",
  },
];